name: Publish SDK to NPM

on:
  release:
    types: [published]

jobs:
  publish-sdk:
    name: Build and publish SDK to NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # For npm provenance

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK
        run: npm run sdk:build

      - name: Run SDK tests
        run: npm run sdk:test

      - name: Test built package
        run: |
          cd packages/js-sdk
          npm run test:package

      - name: Update SDK version to match release
        run: |
          cd packages/js-sdk
          # Extract version from release tag (remove 'v' prefix if present)
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          npm version "$VERSION" --no-git-tag-version
          echo "Updated SDK version to $VERSION"

      - name: Publish to NPM
        run: |
          cd packages/js-sdk
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create SDK release summary
        run: |
          echo "## 📦 SDK Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** \`@llm-crafter/sdk\`" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ github.event.release.tag_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Registry:** [npmjs.com](https://www.npmjs.com/package/@llm-crafter/sdk)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "npm install @llm-crafter/sdk" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
